### ISSUE TITLE
Keyboard input of last used program still active when locked

### ISSUE THREAD

**Issue by brodi1** [jovanlanik/gtklock#38] opened 2022-09-21 20:12 UTC
gtklock version: `1.3.6`
WM: `Hyprland`
OS: `Arch Linux`
modules: `userinfo`

I know this doesn't affect everyone I think but I thought maybe I should report this anyways.

So looks that this only happens under certain conditions.
Normally when my Laptop battery is low swayidle kicks in and locks the screen and since I can type my password fast I once didn't noticed and after I pressed enter I noticed the text input field wasn't focused so I typed my password again and unlocked it and noticed that I accidentally sent someone my password.....luckily I reacted fast enough and I deleted the message 😅 
I tried to reproduce this on sway but seems like it doesn't happen with sway

**Comment by jovanlanik** [comment] 2022-09-21 20:32
Seems to be a duplicate of #37. Can you run `$ WAYLAND_DEBUG=1 gtklock 2>&1 | grep -i inhibit -C 4` and show me the output?

**Comment by jovanlanik** [comment] 2022-09-21 23:05
Closing as duplicate.

**Closed by jovanlanik** 2022-09-21 23:05 UTC
