### ISSUE TITLE
Support for new ext-session-lock-v1 protocol

### ISSUE THREAD

**Issue by MelihDarcanxyz** [jovanlanik/gtklock#53] opened 2023-01-05 18:26 UTC
As compositors switch to new ```ext-session-lock-v1```, gtklock won't be available to use. Therefore, support should be added.

I'm getting this error on latest river release:
```
** (gtklock:38102): CRITICAL **: 21:15:42.023: Your compositor doesn't support wlr-input-inhibitor
```

**Comment by jovanlanik** [comment] 2023-01-07 13:03
Thank you for the report but unfortunately I don't think it's possible at the moment. It comes down to certain limitations of gtk.
I already tried implementing session lock in gtk3 but couldn't get it fully working...
Maybe once gtk4 has a way to use custom surfaces it will be possible.
What this means is when a compositor drops input inhibitor support, gtklock will no longer work on it.

**Comment by jovanlanik** [comment] 2023-01-07 21:49
Also I will leave this issue open because it absolutely is a long term goal.

**Comment by Sunderland93** [comment] 2023-04-22 12:26
gtk-layer-shell now supports GTK 4 https://github.com/wmww/gtk4-layer-shell

**Comment by jovanlanik** [comment] 2023-04-23 12:04
> gtk-layer-shell now supports GTK 4 https://github.com/wmww/gtk4-layer-shell

gtk4 still has no support for custom surfaces... so it's still not possible to support ext-session-lock.
gtk4-layer-shell uses a hacky workaround and my knowledge of gtk and wayland is lacking to implement a similar workaround for ext-session-lock.

But it is possible to port gtklock to gtk4 using the same wlr-input-inhibitor and wlr-layer-shell protocols and I've already started work in the gtk4 branch.

**Comment by RoccoRakete** [comment] 2023-12-12 10:18
How is this going? Because it was mentioned again in https://github.com/jovanlanik/gtklock/issues/80.
Since a recent Hyprland update broke gtklock.

**Comment by aacebedo** [comment] 2023-12-26 09:25
so basically hyprland users have to switch to another locker for the moment ?

**Comment by wenjinnn** [comment] 2023-12-26 09:52
> so basically hyprland users have to switch to another locker for the moment ?

or stay at hyprland v0.32.3 for now.

**Comment by jovanlanik** [comment] 2023-12-26 19:32
> How is this going? Because it was mentioned again in #80. Since a recent Hyprland update broke gtklock.

I am unable to fix gtklock at the moment.
> so basically hyprland users have to switch to another locker for the moment ?

Yes, I recommend all non-sway users switch for the time being.
I'm not sure when sway will drop input-inhibitor but I would expect it soon.

**Comment by ildar** [comment] 2024-01-23 14:14
interesting.
> -i, --no-input-inhibit     Don't use wlr-input-inhibitor
The problem is that locking isn't at all effective with this option. E.g.
it allows to run random apps and commands with Rofi.

**Comment by BowlBird** [comment] 2024-04-02 16:40
Just a heads up, an [awesome library](https://github.com/Cu3PO42/gtk-session-lock) was just made by that allows for usage of the ext-session-lock-v1 protocol in gtk3.

Usage is fairly simple, it was made with AGS in mind, but should work with other GTK3 applications as far as I'm aware.

**Comment by MonstrousOgre** [comment] 2024-04-02 16:47
> Just a heads up, an [awesome library](https://github.com/Cu3PO42/gtk-session-lock) was just made by that allows for usage of the ext-session-lock-v1 protocol in gtk3.
> 
> Usage is fairly simple, it was made with AGS in mind, but should work with other GTK3 applications as far as I'm aware.

That's good to hear. I've switched to hyprlock for now, but gtklock offers more customizability.

**Comment by jovanlanik** [comment] 2024-04-02 22:46
> Just a heads up, an [awesome library](https://github.com/Cu3PO42/gtk-session-lock) was just made by that allows for usage of the ext-session-lock-v1 protocol in gtk3.
> 
> Usage is fairly simple, it was made with AGS in mind, but should work with other GTK3 applications as far as I'm aware.

That really is awesome! I don't have time to try porting now but maybe in the near future...

**Comment by jovanlanik** [comment] 2024-04-07 23:12
If anyone is interested in testing, I did a quick port in the [session-lock](/jovanlanik/gtklock/tree/session-lock) branch.

**Comment by haaase** [comment] 2024-04-08 09:31
> If anyone is interested in testing, I did a quick port in the [session-lock](/jovanlanik/gtklock/tree/session-lock) branch.

I gave the branch a quick try and managed to run it. On hyprland, I can confirm that it does indeed lock the screen, however it did not seem to capture any keyboard input, so it is impossible to enter a password. Mouse input works though, and I can submit the empty password field by clicking.

**Comment by jovanlanik** [comment] 2024-04-15 17:12
Work is being done in this PR #88, I would appreciate anyone willing to test.

**Comment by jovanlanik** [comment] 2024-04-19 13:46
Closing...

**Closed by jovanlanik** 2024-04-19 13:46 UTC
